<?php return array(
    'root' => array(
        'name' => 'artavolo/cms',
        'pretty_version' => 'dev-main',
        'version' => 'dev-main',
        'reference' => '1a6a71d1dcb0f9e30c9a53560704c6cec1704898',
        'type' => 'application',
        'install_path' => __DIR__ . '/../../',
        'aliases' => array(),
        'dev' => true,
    ),
    'versions' => array(
        'artavolo/cms' => array(
            'pretty_version' => 'dev-main',
            'version' => 'dev-main',
            'reference' => '1a6a71d1dcb0f9e30c9a53560704c6cec1704898',
            'type' => 'application',
            'install_path' => __DIR__ . '/../../',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'bacon/bacon-qr-code' => array(
            'pretty_version' => '2.0.7',
            'version' => '2.0.7.0',
            'reference' => 'd70c840f68657ce49094b8d91f9ee0cc07fbf66c',
            'type' => 'library',
            'install_path' => __DIR__ . '/../bacon/bacon-qr-code',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'box/spout' => array(
            'pretty_version' => 'v3.3.0',
            'version' => '3.3.0.0',
            'reference' => '9bdb027d312b732515b884a341c0ad70372c6295',
            'type' => 'library',
            'install_path' => __DIR__ . '/../box/spout',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'braintree/braintree_php' => array(
            'pretty_version' => '6.9.0',
            'version' => '6.9.0.0',
            'reference' => '096984f01c03e47e053703fb159721cb77793587',
            'type' => 'library',
            'install_path' => __DIR__ . '/../braintree/braintree_php',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'clue/stream-filter' => array(
            'pretty_version' => 'v1.6.0',
            'version' => '1.6.0.0',
            'reference' => 'd6169430c7731d8509da7aecd0af756a5747b78e',
            'type' => 'library',
            'install_path' => __DIR__ . '/../clue/stream-filter',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'dapphp/securimage' => array(
            'pretty_version' => 'dev-plumtex-fixes',
            'version' => 'dev-plumtex-fixes',
            'reference' => '87857e7c2f6121a71f571cbf396d6bcb5825621d',
            'type' => 'library',
            'install_path' => __DIR__ . '/../dapphp/securimage',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'dasprid/enum' => array(
            'pretty_version' => '1.0.3',
            'version' => '1.0.3.0',
            'reference' => '5abf82f213618696dda8e3bf6f64dd042d8542b2',
            'type' => 'library',
            'install_path' => __DIR__ . '/../dasprid/enum',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'developermarius/simple-router' => array(
            'pretty_version' => 'dev-plumtex-fixes',
            'version' => 'dev-plumtex-fixes',
            'reference' => 'b226d7a0957b121723597db53e1d8fedc504459c',
            'type' => 'library',
            'install_path' => __DIR__ . '/../developermarius/simple-router',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'developermypos/mypos-checkout-sdk' => array(
            'pretty_version' => '1.2.2',
            'version' => '1.2.2.0',
            'reference' => '9b187a83b0d1cbd4887e7f42f280d3d6ee2f9a13',
            'type' => 'library',
            'install_path' => __DIR__ . '/../developermypos/mypos-checkout-sdk',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'ezyang/htmlpurifier' => array(
            'pretty_version' => 'v4.14.0',
            'version' => '4.14.0.0',
            'reference' => '12ab42bd6e742c70c0a52f7b82477fcd44e64b75',
            'type' => 'library',
            'install_path' => __DIR__ . '/../ezyang/htmlpurifier',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'facebook/graph-sdk' => array(
            'pretty_version' => '5.6.3',
            'version' => '5.6.3.0',
            'reference' => '90e92bd1816fe718e55184ab85910dfcf488432c',
            'type' => 'library',
            'install_path' => __DIR__ . '/../facebook/graph-sdk',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'firebase/php-jwt' => array(
            'pretty_version' => 'v6.2.0',
            'version' => '6.2.0.0',
            'reference' => 'd28e6df83830252650da4623c78aaaf98fb385f3',
            'type' => 'library',
            'install_path' => __DIR__ . '/../firebase/php-jwt',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'genert/bbcode' => array(
            'pretty_version' => '1.1.2',
            'version' => '1.1.2.0',
            'reference' => '8c52c54fe08cc1a38566c7a02d39bc8b3c9453ff',
            'type' => 'library',
            'install_path' => __DIR__ . '/../genert/bbcode',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'google/apiclient' => array(
            'pretty_version' => 'v2.12.4',
            'version' => '2.12.4.0',
            'reference' => '702eed9ae7022ba20dc7118c8161060cb50ee9f8',
            'type' => 'library',
            'install_path' => __DIR__ . '/../google/apiclient',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'google/apiclient-services' => array(
            'pretty_version' => 'v0.249.0',
            'version' => '0.249.0.0',
            'reference' => '95df14183356e45291e1c686cea57850281101db',
            'type' => 'library',
            'install_path' => __DIR__ . '/../google/apiclient-services',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'google/auth' => array(
            'pretty_version' => 'v1.21.0',
            'version' => '1.21.0.0',
            'reference' => '73392bad2eb6852eea9084b6bbdec752515cb849',
            'type' => 'library',
            'install_path' => __DIR__ . '/../google/auth',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'graham-campbell/guzzle-factory' => array(
            'pretty_version' => 'v5.0.3',
            'version' => '5.0.3.0',
            'reference' => 'f93cfbffd422920f5d9915ec7d682f030ddffda6',
            'type' => 'library',
            'install_path' => __DIR__ . '/../graham-campbell/guzzle-factory',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'guzzlehttp/guzzle' => array(
            'pretty_version' => '7.5.1',
            'version' => '7.5.1.0',
            'reference' => 'b964ca597e86b752cd994f27293e9fa6b6a95ed9',
            'type' => 'library',
            'install_path' => __DIR__ . '/../guzzlehttp/guzzle',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'guzzlehttp/promises' => array(
            'pretty_version' => '1.5.2',
            'version' => '1.5.2.0',
            'reference' => 'b94b2807d85443f9719887892882d0329d1e2598',
            'type' => 'library',
            'install_path' => __DIR__ . '/../guzzlehttp/promises',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'guzzlehttp/psr7' => array(
            'pretty_version' => '2.5.0',
            'version' => '2.5.0.0',
            'reference' => 'b635f279edd83fc275f822a1188157ffea568ff6',
            'type' => 'library',
            'install_path' => __DIR__ . '/../guzzlehttp/psr7',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'krizalys/onedrive-php-sdk' => array(
            'pretty_version' => '3.1.0',
            'version' => '3.1.0.0',
            'reference' => 'a300e86c855aefc35d5ef37ce8a69a8b61ccedea',
            'type' => 'library',
            'install_path' => __DIR__ . '/../krizalys/onedrive-php-sdk',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'league/oauth2-client' => array(
            'pretty_version' => '2.6.1',
            'version' => '2.6.1.0',
            'reference' => '2334c249907190c132364f5dae0287ab8666aa19',
            'type' => 'library',
            'install_path' => __DIR__ . '/../league/oauth2-client',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'league/oauth2-github' => array(
            'pretty_version' => '3.1.0',
            'version' => '3.1.0.0',
            'reference' => '97f31cd70e76f81e8f5b4e2ab6f3708e2db7ac18',
            'type' => 'library',
            'install_path' => __DIR__ . '/../league/oauth2-github',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'league/omnipay' => array(
            'pretty_version' => 'v3.2.1',
            'version' => '3.2.1.0',
            'reference' => '38f66a0cc043ed51d6edf7956d6439a2f263501f',
            'type' => 'metapackage',
            'install_path' => NULL,
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'maennchen/zipstream-php' => array(
            'pretty_version' => '2.2.1',
            'version' => '2.2.1.0',
            'reference' => '211e9ba1530ea5260b45d90c9ea252f56ec52729',
            'type' => 'library',
            'install_path' => __DIR__ . '/../maennchen/zipstream-php',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'mailchimp/marketing' => array(
            'pretty_version' => '3.0.75',
            'version' => '3.0.75.0',
            'reference' => '759e043ecce64c2374f05fcd600b69a3d1583b8c',
            'type' => 'library',
            'install_path' => __DIR__ . '/../mailchimp/marketing',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'markbaker/complex' => array(
            'pretty_version' => '3.0.1',
            'version' => '3.0.1.0',
            'reference' => 'ab8bc271e404909db09ff2d5ffa1e538085c0f22',
            'type' => 'library',
            'install_path' => __DIR__ . '/../markbaker/complex',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'markbaker/matrix' => array(
            'pretty_version' => '3.0.0',
            'version' => '3.0.0.0',
            'reference' => 'c66aefcafb4f6c269510e9ac46b82619a904c576',
            'type' => 'library',
            'install_path' => __DIR__ . '/../markbaker/matrix',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'microsoft/microsoft-graph' => array(
            'pretty_version' => '1.85.0',
            'version' => '1.85.0.0',
            'reference' => 'e1759262669941873647d0036956239bffb06a2d',
            'type' => 'library',
            'install_path' => __DIR__ . '/../microsoft/microsoft-graph',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'moneyphp/money' => array(
            'pretty_version' => 'v4.0.4',
            'version' => '4.0.4.0',
            'reference' => 'efe904ab6109d87046eb624d5dff7d270fd0cca5',
            'type' => 'library',
            'install_path' => __DIR__ . '/../moneyphp/money',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'monolog/monolog' => array(
            'pretty_version' => '2.6.0',
            'version' => '2.6.0.0',
            'reference' => '247918972acd74356b0a91dfaa5adcaec069b6c0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../monolog/monolog',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'myclabs/php-enum' => array(
            'pretty_version' => '1.8.3',
            'version' => '1.8.3.0',
            'reference' => 'b942d263c641ddb5190929ff840c68f78713e937',
            'type' => 'library',
            'install_path' => __DIR__ . '/../myclabs/php-enum',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'omnipay/common' => array(
            'pretty_version' => 'v3.2.0',
            'version' => '3.2.0.0',
            'reference' => 'e278ff00676c05cd0f4aaaf6189a226f26ae056e',
            'type' => 'library',
            'install_path' => __DIR__ . '/../omnipay/common',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'omnipay/paypal' => array(
            'pretty_version' => 'v3.0.2',
            'version' => '3.0.2.0',
            'reference' => '519db61b32ff0c1e56cbec94762b970ee9674f65',
            'type' => 'library',
            'install_path' => __DIR__ . '/../omnipay/paypal',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'openai-php/client' => array(
            'pretty_version' => 'v0.4.2',
            'version' => '0.4.2.0',
            'reference' => 'bbfbc0a28872d679d6990712d7feaae2c9f96fc2',
            'type' => 'library',
            'install_path' => __DIR__ . '/../openai-php/client',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'paragonie/constant_time_encoding' => array(
            'pretty_version' => 'v2.5.0',
            'version' => '2.5.0.0',
            'reference' => '9229e15f2e6ba772f0c55dd6986c563b937170a8',
            'type' => 'library',
            'install_path' => __DIR__ . '/../paragonie/constant_time_encoding',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'paragonie/random_compat' => array(
            'pretty_version' => 'v9.99.100',
            'version' => '9.99.100.0',
            'reference' => '996434e5492cb4c3edcb9168db6fbb1359ef965a',
            'type' => 'library',
            'install_path' => __DIR__ . '/../paragonie/random_compat',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'paragonie/sodium_compat' => array(
            'pretty_version' => 'v1.19.0',
            'version' => '1.19.0.0',
            'reference' => 'cb15e403ecbe6a6cc515f855c310eb6b1872a933',
            'type' => 'library',
            'install_path' => __DIR__ . '/../paragonie/sodium_compat',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'paypal/rest-api-sdk-php' => array(
            'pretty_version' => '1.14.0',
            'version' => '1.14.0.0',
            'reference' => '72e2f2466975bf128a31e02b15110180f059fc04',
            'type' => 'library',
            'install_path' => __DIR__ . '/../paypal/rest-api-sdk-php',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'php-http/async-client-implementation' => array(
            'dev_requirement' => false,
            'provided' => array(
                0 => '*',
                1 => '1.0',
            ),
        ),
        'php-http/client-implementation' => array(
            'dev_requirement' => false,
            'provided' => array(
                0 => '*',
                1 => '1.0',
            ),
        ),
        'php-http/discovery' => array(
            'pretty_version' => '1.18.0',
            'version' => '1.18.0.0',
            'reference' => '29ae6fae35f4116bbfe4c8b96ccc3f687eb07cd9',
            'type' => 'composer-plugin',
            'install_path' => __DIR__ . '/../php-http/discovery',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'php-http/guzzle7-adapter' => array(
            'pretty_version' => '1.0.0',
            'version' => '1.0.0.0',
            'reference' => 'fb075a71dbfa4847cf0c2938c4e5a9c478ef8b01',
            'type' => 'library',
            'install_path' => __DIR__ . '/../php-http/guzzle7-adapter',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'php-http/httplug' => array(
            'pretty_version' => '2.3.0',
            'version' => '2.3.0.0',
            'reference' => 'f640739f80dfa1152533976e3c112477f69274eb',
            'type' => 'library',
            'install_path' => __DIR__ . '/../php-http/httplug',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'php-http/message' => array(
            'pretty_version' => '1.13.0',
            'version' => '1.13.0.0',
            'reference' => '7886e647a30a966a1a8d1dad1845b71ca8678361',
            'type' => 'library',
            'install_path' => __DIR__ . '/../php-http/message',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'php-http/message-factory' => array(
            'pretty_version' => '1.1.0',
            'version' => '1.1.0.0',
            'reference' => '4d8778e1c7d405cbb471574821c1ff5b68cc8f57',
            'type' => 'library',
            'install_path' => __DIR__ . '/../php-http/message-factory',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'php-http/message-factory-implementation' => array(
            'dev_requirement' => false,
            'provided' => array(
                0 => '1.0',
            ),
        ),
        'php-http/multipart-stream-builder' => array(
            'pretty_version' => '1.3.0',
            'version' => '1.3.0.0',
            'reference' => 'f5938fd135d9fa442cc297dc98481805acfe2b6a',
            'type' => 'library',
            'install_path' => __DIR__ . '/../php-http/multipart-stream-builder',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'php-http/promise' => array(
            'pretty_version' => '1.1.0',
            'version' => '1.1.0.0',
            'reference' => '4c4c1f9b7289a2ec57cde7f1e9762a5789506f88',
            'type' => 'library',
            'install_path' => __DIR__ . '/../php-http/promise',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'phpmailer/phpmailer' => array(
            'pretty_version' => 'v6.6.0',
            'version' => '6.6.0.0',
            'reference' => 'e43bac82edc26ca04b36143a48bde1c051cfd5b1',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpmailer/phpmailer',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'phpoffice/phpspreadsheet' => array(
            'pretty_version' => '1.23.0',
            'version' => '1.23.0.0',
            'reference' => '21e4cf62699eebf007db28775f7d1554e612ed9e',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpoffice/phpspreadsheet',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'phpseclib/phpseclib' => array(
            'pretty_version' => '3.0.14',
            'version' => '3.0.14.0',
            'reference' => '2f0b7af658cbea265cbb4a791d6c29a6613f98ef',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpseclib/phpseclib',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'pragmarx/google2fa' => array(
            'pretty_version' => '8.0.0',
            'version' => '8.0.0.0',
            'reference' => '26c4c5cf30a2844ba121760fd7301f8ad240100b',
            'type' => 'library',
            'install_path' => __DIR__ . '/../pragmarx/google2fa',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'psr/cache' => array(
            'pretty_version' => '3.0.0',
            'version' => '3.0.0.0',
            'reference' => 'aa5030cfa5405eccfdcb1083ce040c2cb8d253bf',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/cache',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'psr/http-client' => array(
            'pretty_version' => '1.0.2',
            'version' => '1.0.2.0',
            'reference' => '0955afe48220520692d2d09f7ab7e0f93ffd6a31',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/http-client',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'psr/http-client-implementation' => array(
            'dev_requirement' => false,
            'provided' => array(
                0 => '1.0',
                1 => '*',
            ),
        ),
        'psr/http-factory' => array(
            'pretty_version' => '1.0.2',
            'version' => '1.0.2.0',
            'reference' => 'e616d01114759c4c489f93b099585439f795fe35',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/http-factory',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'psr/http-factory-implementation' => array(
            'dev_requirement' => false,
            'provided' => array(
                0 => '1.0',
                1 => '*',
            ),
        ),
        'psr/http-message' => array(
            'pretty_version' => '1.1',
            'version' => '1.1.0.0',
            'reference' => 'cb6ce4845ce34a8ad9e68117c10ee90a29919eba',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/http-message',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'psr/http-message-implementation' => array(
            'dev_requirement' => false,
            'provided' => array(
                0 => '1.0',
                1 => '*',
            ),
        ),
        'psr/log' => array(
            'pretty_version' => '1.1.4',
            'version' => '1.1.4.0',
            'reference' => 'd49695b909c3b7628b6289db5479a1c204601f11',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/log',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'psr/log-implementation' => array(
            'dev_requirement' => false,
            'provided' => array(
                0 => '1.0.0 || 2.0.0 || 3.0.0',
            ),
        ),
        'psr/simple-cache' => array(
            'pretty_version' => '2.0.0',
            'version' => '2.0.0.0',
            'reference' => '8707bf3cea6f710bf6ef05491234e3ab06f6432a',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/simple-cache',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'pusher/pusher-php-server' => array(
            'pretty_version' => '7.2.2',
            'version' => '7.2.2.0',
            'reference' => '4ace4873873b06c25cecb2dd6d9fdcbf2f20b640',
            'type' => 'library',
            'install_path' => __DIR__ . '/../pusher/pusher-php-server',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'pusher/pusher-push-notifications' => array(
            'pretty_version' => '2.0',
            'version' => '2.0.0.0',
            'reference' => '6ec015243c18b0579c261c2decef99324d7452b9',
            'type' => 'library',
            'install_path' => __DIR__ . '/../pusher/pusher-push-notifications',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'pyovchevski/php-image-magician' => array(
            'pretty_version' => 'dev-master',
            'version' => 'dev-master',
            'reference' => '004bca4f9a117b5eb7a5e3a4469f90f573cc4ebf',
            'type' => 'library',
            'install_path' => __DIR__ . '/../pyovchevski/php-image-magician',
            'aliases' => array(
                0 => '9999999-dev',
            ),
            'dev_requirement' => false,
        ),
        'ralouphie/getallheaders' => array(
            'pretty_version' => '3.0.3',
            'version' => '3.0.3.0',
            'reference' => '120b605dfeb996808c31b6477290a714d356e822',
            'type' => 'library',
            'install_path' => __DIR__ . '/../ralouphie/getallheaders',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'somnambulist/validation' => array(
            'pretty_version' => '1.6.0',
            'version' => '1.6.0.0',
            'reference' => '6b20a6123504f6703d8efefba89e588908d91a6c',
            'type' => 'library',
            'install_path' => __DIR__ . '/../somnambulist/validation',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'spatie/dropbox-api' => array(
            'pretty_version' => '1.21.0',
            'version' => '1.21.0.0',
            'reference' => '0fec337ca1244f21f0467f73a43893f7bd7fdcdb',
            'type' => 'library',
            'install_path' => __DIR__ . '/../spatie/dropbox-api',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'stevenmaguire/oauth2-dropbox' => array(
            'pretty_version' => '2.0.0',
            'version' => '2.0.0.0',
            'reference' => '01c37ed9ce190569450e6a4bdee90204eb8600a0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../stevenmaguire/oauth2-dropbox',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'stripe/stripe-php' => array(
            'pretty_version' => 'v10.9.1',
            'version' => '10.9.1.0',
            'reference' => 'be1de500a70b9eada6dbe72b0c8e21c845570903',
            'type' => 'library',
            'install_path' => __DIR__ . '/../stripe/stripe-php',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/deprecation-contracts' => array(
            'pretty_version' => 'v3.2.1',
            'version' => '3.2.1.0',
            'reference' => 'e2d1534420bd723d0ef5aec58a22c5fe60ce6f5e',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/deprecation-contracts',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/http-foundation' => array(
            'pretty_version' => 'v6.0.8',
            'version' => '6.0.8.0',
            'reference' => 'c9c86b02d7ef6f44f3154acc7de42831518afe7c',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/http-foundation',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/polyfill-mbstring' => array(
            'pretty_version' => 'v1.27.0',
            'version' => '1.27.0.0',
            'reference' => '8ad114f6b39e2c98a8b0e3bd907732c207c2b534',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-mbstring',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'twilio/sdk' => array(
            'pretty_version' => '6.43.0',
            'version' => '6.43.0.0',
            'reference' => '687245ed07dc807eec94389f715323cf13c1e316',
            'type' => 'library',
            'install_path' => __DIR__ . '/../twilio/sdk',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'workerman/workerman' => array(
            'pretty_version' => 'v4.0.39',
            'version' => '4.0.39.0',
            'reference' => '97ff0d0d3d20ce9abfd0f3c87e5e3481d3bf16d9',
            'type' => 'library',
            'install_path' => __DIR__ . '/../workerman/workerman',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
    ),
);
